spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://127.0.0.1:5432/LevioCoin"
    username: postgres
    password: root1234
