spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://leviocoin2.czlptflqfzfa.us-east-1.rds.amazonaws.com:5432/LevioCoin"
    username: postgres
    password: Qf7qw%wrVL)cXrXxb
